Function builtin expanded notation
ericelliott/rtype pull request #142
Opened 2018-09-06 20:50 UTC by Mouvedia

This detail was missing from the specification.

2018-10-05 20:12 UTC, ericelliott commented on README.md
> +Note: the `Function` builtin type expands to `(...args: [...Any]) => Void`.
Shouldn't that be `(...args: [...Any]) => Any`?

2018-10-05 20:13 UTC, ericelliott requested changes
See question.

2018-10-05 20:26 UTC, Mouvedia commented on README.md
> +Note: the `Function` builtin type expands to `(...args: [...Any]) => Void`.
Since `Any` encompasses `Void` it shouldn't matter but in my experience returning `undefined` is the canonical default behaviour. You are probably right.

2018-10-05 20:27 UTC, Mouvedia commented
@ericelliott if it becomes `=> Any` we will have to move that note somewhere else.

2018-10-05 20:42 UTC, Mouvedia commented
@ericelliott I don't wanna be annoying but better be safe than sorry: squash the commits.

2018-10-06 00:26 UTC, ericelliott commented
Why?

2018-10-06 00:34 UTC, Mouvedia commented
To have a clean history? One commit per PR seems better. **And** GitHub supports it in its interface directly.

2018-10-06 01:37 UTC, ericelliott commented
I prefer a more complete and accurate history.

2018-10-06 01:40 UTC, ericelliott commented on README.md
> +Note: the `Function` builtin type expands to `(...args: [...Any]) => Void`.
`Any` encompases `Void`, but by default, any function should pass this test, and very few pure functions would. ;)

2018-10-06 01:49 UTC, Mouvedia commented
Here's a blog post that explains it in details: https://blog.github.com/2016-04-01-squash-your-commits/#enter-commit-squashing

On all the open sources projects that Iv contribute to, the maintainer squash the commits that results from the review. It's not my pet peeve, it's just a convention on GitHub.

2018-10-06 14:13 UTC, ericelliott commented
Ah, so pet peeve. ;)

2018-10-06 14:19 UTC, Mouvedia commented
You should not be proud of having `Update README.md` for almost all of your commit messages :)

Well anyway, we are not on the same page on this so Ill squash myself.

2018-10-06 14:50 UTC, Mouvedia commented
@ericelliott LGTM

2018-10-08 01:03 UTC, merged

2018-10-08 01:03 UTC, ericelliott commented
> You should not be proud of having Update README.md for almost all of your commit messages :)

We should be more descriptive about what feature we're updating. =)